### ISSUE TITLE
End of line styling conflict with default behavior in Magit buffer.

### ISSUE THREAD

**Issue by proofit404** [abo-abo/eclipse-theme#10]
Hi, as [it was reported yesterday](https://github.com/abo-abo/eclipse-theme/issues/9) new lines style has a conflict with default behavior.

Looks like Magit buffers needs additional attention.

![Untitled](https://user-images.githubusercontent.com/1862725/68757474-0a02df00-061d-11ea-97f1-a7f8dd599b06.png)

Package version: 20191112.1008

Have a good day :tada:

Best regards,
Artem.

**Comment by abo-abo** [comment]
Thanks, please test.
