### ISSUE TITLE
Weird color in minibuffer

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/eclipse-theme#2]
I like your theme, nice work. You can guess that I too use eclipse a lot.

Couple of suggestions:
1) I have global-hl-line-mode enabled, and the default line highlight color is a bit too dark for comfortable viewing of the text. This might happen for other users as well.

Currently I am not sure whether this is due to the theme settings or some of my packages. So I override it with 
(set-face-background 'hl-line "#e5e4e2") ;; platinum color

2) The minibuffer completion shows red color when narrowing down the list. Here is a snapshot, I am not sure whether this is by design. 

![screenshot](https://cloud.githubusercontent.com/assets/7343807/6510441/004c7d26-c334-11e4-98e5-a1d6c2c8934c.png)

**Comment by abo-abo** [comment]
> You can guess that I too use eclipse a lot

You must have either the patience or dire need. I haven't seen Eclipse in four years.

> (set-face-background 'hl-line "#e5e4e2") ;; platinum color

I can set this, it looks OK to me, although I never use `global-hl-line-mode`.

> The minibuffer completion shows red color when narrowing down the list

The last issue isn't related to the theme. It seems that you're having a weird clash between
`ido-vertical` and `whitespace-mode`. I've never encountered it. Try turning off some
packages until the issue disappears.
