### ISSUE TITLE
Why the plain face for outline-2?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/eclipse-theme#5]
Came to this theme from your screencasts, enjoy it very much. Don't you get confused in org-mode when the second heading is indistinguishable from body text? Feel like they could be visually distinguished more.

**Comment by abo-abo** [comment]
> enjoy it very much

Thanks, I thought I was the only one.

> Don't you get confused in org-mode when the second heading is indistinguishable from body text? Feel like they could be visually distinguished more.

This is due to the inheritance `org-level-2` <- `outline-2` <- `font-lock-variable-name-face`.  I've customized only the last one.  If you give a good suggestion for `org-level-2`, which I haven't customized yet, I'll set it.

**Comment by sooheon** [comment]
No good suggestion for org-level-2 yet, but I noticed that org-level-5 was customised specifically to be empty face, maybe it should inherit outline-5?

**Comment by abo-abo** [comment]
The reasoning is similar here: `org-level-5` <- `outline-5` <- `font-lock-type-face`.
But I have `font-lock-type-face` with underline: it looks nice for types, but bad for `org-level-5`.
