### ISSUE TITLE
dejavu is good, but

### ISSUE THREAD

**Issue by habamax** [abo-abo/eclipse-theme#6]
I believe font-settings should not be included into theme:

```
 `((default :family "DejaVu Sans Mono"
              :height 113
              :foreground ,eclipse-fg
              :background ,eclipse-bg)
```

I use source code pro and don't have dejavu installed thus eclipse-theme makes funky job with my emacs :)

**Comment by manuel-uberti** [comment]
I was about to point that out too. I use DejaVu Sans Mono, but with a different height.

**Comment by abo-abo** [comment]
Thanks.

**Comment by manuel-uberti** [comment]
Thank you for the quick fix, looks perfect now.
