### ISSUE TITLE
Powerline Mode Line

### ISSUE THREAD

**Issue by it6** [abo-abo/eclipse-theme#7]
I am on Mac OSX Sierra I installed eclipse theme along with powerline font Dejavu Mono, but my modeline still looks normal. 

<img width="1440" alt="screen shot 2017-08-05 at 3 43 55 pm" src="https://user-images.githubusercontent.com/5510191/28998278-efc595e4-79f4-11e7-8775-ed3c2323175b.png">

Is there anything else I need to do, I like the power line fonts in the mode line.

**Comment by abo-abo** [comment]
Install `powerline`.

```elisp
(when (image-type-available-p 'xpm)
  (use-package powerline
      :config
    (setq powerline-display-buffer-size nil)
    (setq powerline-display-mule-info nil)
    (setq powerline-display-hud nil)
    (when (display-graphic-p)
      (powerline-default-theme)
      (remove-hook 'focus-out-hook 'powerline-unset-selected-window))))
```
