### ISSUE TITLE
End of line styling conflict with default behavior.

### ISSUE THREAD

**Issue by proofit404** [abo-abo/eclipse-theme#9]
Hi, thanks for the awesome theme!

Some time ago styling of the end of lines changed for me.

It was:
![Untitled](https://user-images.githubusercontent.com/1862725/68658010-bd000980-0545-11ea-9a33-ea244d21a2ea.png)

It is now:
![Untitled1](https://user-images.githubusercontent.com/1862725/68658048-cbe6bc00-0545-11ea-8a65-6edbac6d1410.png)

My emacs version:
```
GNU Emacs 27.0.50
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```
I believe there was some thread about that on the Hacker News.

Is it possible to support both styles in the theme?

Have a good day :tada: 

Best regards,
Artem.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by proofit404** [comment]
Works perfectly! Thanks!
